# Generated by Django 3.1.3 on 2022-01-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220107_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_certified',
            field=models.BooleanField(default=False),
        ),
    ]
