# Generated by Django 3.1.3 on 2022-01-05 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220105_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_1', models.ImageField(upload_to='static/images/posts')),
                ('pic_2', models.ImageField(upload_to='static/images/posts')),
                ('pic_3', models.ImageField(upload_to='static/images/posts')),
                ('pic_4', models.ImageField(upload_to='static/images/posts')),
                ('pic_5', models.ImageField(upload_to='static/images/posts')),
                ('pic_6', models.ImageField(upload_to='static/images/posts')),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.post')),
            ],
        ),
    ]
