# Generated by Django 3.1.3 on 2022-01-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
