# Generated by Django 3.1.3 on 2022-01-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20220105_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_image',
            name='pic_1',
            field=models.ImageField(blank=True, upload_to='static/images/posts'),
        ),
        migrations.AlterField(
            model_name='post_image',
            name='pic_2',
            field=models.ImageField(blank=True, upload_to='static/images/posts'),
        ),
        migrations.AlterField(
            model_name='post_image',
            name='pic_3',
            field=models.ImageField(blank=True, upload_to='static/images/posts'),
        ),
        migrations.AlterField(
            model_name='post_image',
            name='pic_4',
            field=models.ImageField(blank=True, upload_to='static/images/posts'),
        ),
        migrations.AlterField(
            model_name='post_image',
            name='pic_5',
            field=models.ImageField(blank=True, upload_to='static/images/posts'),
        ),
        migrations.AlterField(
            model_name='post_image',
            name='pic_6',
            field=models.ImageField(blank=True, upload_to='static/images/posts'),
        ),
    ]
